---
proxmox_user: root@pam
proxmox_password:
proxmox_host: 192.168.4.2
proxmox_node: pve
vm_id: 101
vm_cores: 2
vm_memory: 2048
vm_disk_name: scsi0
vm_disk_size: 10G
vm_ip: 192.168.4.10
vm_gateway_ip: 192.168.4.1
vm_cpu_type: host
timeout: 500
